name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-win:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Msys2
      uses: msys2/setup-msys2@v2
      with:
        install: mingw64/mingw-w64-x86_64-clang
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
